"use client";

import { useEffect, useRef, useState } from "react";
import { fallbackChat } from "@/lib/ai";

type Role="patient"|"doctor"|"admin";
type Message={author:"assistant"|"user";text:string;urgency?:string;specialty?:string;nextSteps?:string[];source?:string};

function Glyph({type,size=18}:{type:"spark"|"send"|"close"|"shield"|"plus"|"check"|"doctor"|"pill";size?:number}){const paths={spark:<path d="m12 3 1.9 5.8L20 11l-6.1 2.2L12 19l-1.9-5.8L4 11l6.1-2.2L12 3Z"/>,send:<path d="m22 2-7 20-4-9-9-4 20-7Zm-11 11 11-11"/>,close:<path d="m18 6-12 12M6 6l12 12"/>,shield:<><path d="M12 22s8-4 8-11V5l-8-3-8 3v6c0 7 8 11 8 11Z"/><path d="m9 12 2 2 4-4"/></>,plus:<path d="M12 5v14M5 12h14"/>,check:<path d="m5 12 4 4L19 6"/>,doctor:<><path d="M4 3v5a5 5 0 0 0 10 0V3m-5 10v2a6 6 0 0 0 12 0v-2"/><circle cx="21" cy="11" r="2"/></>,pill:<path d="m10.5 20.5 10-10a5 5 0 0 0-7-7l-10 10a5 5 0 0 0 7 7ZM8.5 8.5l7 7"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[type]}</svg>}

export function CareAssistant({role,open,setOpen,onNotice}:{role:Role;open:boolean;setOpen:(open:boolean)=>void;onNotice:(message:string)=>void}){
  const starters=role==="patient"?["I have a headache and mild dizziness","Help me prepare for my cardiology visit","When should I take my prescribed medicine?"]:role==="doctor"?["Summarise symptoms of chest discomfort with exertion","What questions should I ask about palpitations?","Prepare patient-friendly follow-up instructions"]:["How should I handle doctor leave conflicts?","Explain why medication reminders are retrying","What should I check before cancelling a booking?"];
  const [messages,setMessages]=useState<Message[]>([{author:"assistant",text:role==="patient"?"Hi, I’m your MediFlow care assistant. Tell me how you’re feeling, ask about an appointment, or describe a symptom and I’ll help you find the right next step.":role==="doctor"?"I can help organise patient symptoms, suggest non-diagnostic clinical questions, and turn visit notes into clear patient guidance.":"I can explain appointment conflicts, care continuity alerts, reminder delivery, and operational next steps."}]);
  const [input,setInput]=useState("");const [loading,setLoading]=useState(false);const end=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{end.current?.scrollIntoView({block:"nearest"})},[messages,loading]);
  async function send(value=input){const text=value.trim();if(!text||loading)return;setInput("");setMessages(current=>[...current,{author:"user",text}]);setLoading(true);try{const response=await fetch("/api/ai/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text}),signal:AbortSignal.timeout(12000)});const result=await response.json() as {reply?:{message:string;urgency:string;suggestedSpecialty:string;nextSteps:string[];source:string};error?:string};if(!response.ok||!result.reply)throw new Error(result.error||"Assistant service unavailable");setMessages(current=>[...current,{author:"assistant",text:result.reply!.message,urgency:result.reply!.urgency,specialty:result.reply!.suggestedSpecialty,nextSteps:result.reply!.nextSteps,source:result.reply!.source}]);}catch{const safe=fallbackChat(text);setMessages(current=>[...current,{author:"assistant",text:safe.message,urgency:safe.urgency,specialty:safe.suggestedSpecialty,nextSteps:safe.nextSteps,source:"fallback"}]);onNotice("Care assistant is available using its safe local fallback")}finally{setLoading(false)}}
  return <><button className="care-fab" onClick={()=>setOpen(!open)} aria-label={open?"Close care assistant":"Open care assistant"}>{open?<Glyph type="close" size={21}/>:<Glyph type="spark" size={21}/>}<span>{open?"Close":"Ask MediFlow AI"}</span></button>{open&&<section className="care-chat-panel"><header className="care-chat-header"><div><span><Glyph type="spark" size={19}/></span><div><strong>MediFlow care assistant</strong><small><i/> Available now · Safe clinical guidance</small></div></div><button onClick={()=>setOpen(false)} aria-label="Close assistant"><Glyph type="close" size={18}/></button></header><div className="care-chat-messages">{messages.map((message,index)=><article key={index} className={`care-message care-message-${message.author}`}><div>{message.text}</div>{message.urgency&&<aside className={`care-triage care-triage-${message.urgency}`}><strong>{message.urgency.toUpperCase()} PRIORITY · {message.specialty}</strong>{message.nextSteps&&<ul>{message.nextSteps.map(step=><li key={step}>{step}</li>)}</ul>}</aside>}{message.source&&<small>{message.source==="model"?"AI-generated":"Safe offline fallback"} · Not a diagnosis</small>}</article>)}{loading&&<div className="care-thinking"><span/><span/><span/> Preparing a helpful answer</div>}<div ref={end}/></div>{messages.length===1&&<div className="care-starters">{starters.map(starter=><button key={starter} onClick={()=>send(starter)}>{starter}</button>)}</div>}<form className="care-chat-form" onSubmit={event=>{event.preventDefault();void send()}}><input value={input} onChange={event=>setInput(event.target.value)} placeholder="Describe symptoms or ask a question..." disabled={loading}/><button type="submit" disabled={!input.trim()||loading} aria-label="Send message"><Glyph type="send" size={17}/></button></form><div className="care-chat-disclaimer"><Glyph type="shield" size={13}/> Informational support only. In an emergency, seek immediate medical help.</div></section>}</>;
}

export function VisitComposer({patientName,doctorName,onClose,onSaved}:{patientName:string;doctorName:string;onClose:()=>void;onSaved:(message:string)=>void}){
  const [notes,setNotes]=useState("Patient reports intermittent chest discomfort during exertion. Discussed blood pressure monitoring, symptom tracking, and follow-up in seven days.");const [medicine,setMedicine]=useState("Amlodipine");const [dosage,setDosage]=useState("5 mg");const [frequency,setFrequency]=useState("Once daily");const [duration,setDuration]=useState("7");const [saving,setSaving]=useState(false);const [summary,setSummary]=useState<{summary:string;medicationSchedule:string[];followUpSteps:string[];urgentWarning:string;source:string}|null>(null);const [error,setError]=useState("");
  async function save(){setSaving(true);setError("");try{const listResponse=await fetch(`/api/appointments?patientName=${encodeURIComponent(patientName)}`);const list=await listResponse.json() as {appointments?:{id:string;doctor_name:string;status:string}[]};let appointmentId=list.appointments?.find(item=>item.doctor_name===doctorName&&item.status!=="cancelled")?.id;if(!appointmentId){const date=new Date();const localDate=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")} ${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`;const booked=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({doctorName,patientName,scheduledFor:localDate,symptoms:notes})});const booking=await booked.json() as {appointment?:{id:string};error?:string};if(!booked.ok||!booking.appointment)throw new Error(booking.error||"Create an appointment before completing this visit.");appointmentId=booking.appointment.id}const response=await fetch("/api/visits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({appointmentId,notes,medications:medicine.trim()?[{medicationName:medicine,dosage,frequency,durationDays:Number(duration)||7,instructions:"Take after food"}]:[]})});const result=await response.json() as {summary?:typeof summary;prescriptionsCreated?:number;medicationRemindersQueued?:number;error?:string};if(!response.ok||!result.summary)throw new Error(result.error||"Could not save the visit.");setSummary(result.summary);onSaved(`Visit saved: ${result.prescriptionsCreated||0} prescription and ${result.medicationRemindersQueued||0} reminders queued`)}catch(err){setError(err instanceof Error?err.message:"Could not save the visit")}finally{setSaving(false)}}
  return <div className="modal-backdrop" onClick={onClose}><div className="booking-modal clinical-modal" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close"><Glyph type="close"/></button><p className="eyebrow">DOCTOR WORKSPACE · POST-VISIT CARE</p><h2>{summary?"Your patient-ready summary":"Complete clinical visit"}</h2><div className="clinical-person"><Glyph type="doctor"/><span><strong>{patientName}</strong><small>{doctorName}</small></span></div>{summary?<><div className="clinical-summary"><h3>What we discussed</h3><p>{summary.summary}</p><h3>Your medication schedule</h3><ul>{summary.medicationSchedule.map(item=><li key={item}>{item}</li>)}</ul><h3>Follow-up steps</h3><ul>{summary.followUpSteps.map(item=><li key={item}>{item}</li>)}</ul><p className="clinical-warning">{summary.urgentWarning}</p></div><button className="button button-primary full-width" onClick={onClose}><Glyph type="check" size={16}/> Done</button></>:<><label className="clinical-label">Clinical visit notes</label><textarea className="clinical-notes" value={notes} onChange={event=>setNotes(event.target.value)}/><label className="clinical-label">Prescription</label><div className="clinical-medicine"><input value={medicine} onChange={event=>setMedicine(event.target.value)} placeholder="Medication"/><input value={dosage} onChange={event=>setDosage(event.target.value)} placeholder="Dosage"/></div><div className="clinical-medicine"><select value={frequency} onChange={event=>setFrequency(event.target.value)}><option>Once daily</option><option>Twice daily</option><option>Three times daily</option></select><input value={duration} onChange={event=>setDuration(event.target.value)} placeholder="Days"/></div><div className="clinical-ai-note"><Glyph type="spark" size={17}/> AI will prepare a patient-friendly summary and schedule reminders.</div>{error&&<p className="clinical-error">{error}</p>}<button className="button button-primary full-width" onClick={()=>void save()} disabled={saving||!notes.trim()}>{saving?"Saving visit...":"Save visit & generate summary"}</button></>}</div></div>;
}

export function DoctorProfileForm({onClose,onSaved}:{onClose:()=>void;onSaved:(message:string)=>void}){
  const [name,setName]=useState("");const [email,setEmail]=useState("");const [specialty,setSpecialty]=useState("Cardiology");const [hours,setHours]=useState("Mon–Fri, 9:00 AM–5:00 PM");const [duration,setDuration]=useState("30");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  async function save(){setSaving(true);setError("");try{const response=await fetch("/api/doctors",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,specialty,workingHours:hours,slotDurationMinutes:Number(duration)})});const result=await response.json() as {doctor?:{name:string};error?:string};if(!response.ok||!result.doctor)throw new Error(result.error||"Doctor profile could not be saved");onSaved(`${result.doctor.name} was added to the care team and saved in the database`);onClose()}catch(err){setError(err instanceof Error?err.message:"Could not save the doctor")}finally{setSaving(false)}}
  return <div className="modal-backdrop" onClick={onClose}><div className="booking-modal clinical-modal" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close"><Glyph type="close"/></button><p className="eyebrow">ADMIN WORKSPACE · CARE TEAM</p><h2>Add a doctor profile</h2><label className="clinical-label">Full name</label><input className="clinical-input" value={name} onChange={event=>setName(event.target.value)} placeholder="Dr. Aarav Kulkarni"/><label className="clinical-label">Work email</label><input className="clinical-input" type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="aarav@mediflow.health"/><label className="clinical-label">Specialisation</label><select className="clinical-input" value={specialty} onChange={event=>setSpecialty(event.target.value)}><option>Cardiology</option><option>Dermatology</option><option>Neurology</option><option>General physician</option><option>Gynaecology</option><option>Orthopaedics</option></select><div className="clinical-medicine"><div><label className="clinical-label">Working hours</label><input className="clinical-input" value={hours} onChange={event=>setHours(event.target.value)}/></div><div><label className="clinical-label">Slot duration</label><select className="clinical-input" value={duration} onChange={event=>setDuration(event.target.value)}><option value="15">15 min</option><option value="30">30 min</option><option value="45">45 min</option><option value="60">60 min</option></select></div></div>{error&&<p className="clinical-error">{error}</p>}<button className="button button-primary full-width" onClick={()=>void save()} disabled={saving||!name.trim()||!email.trim()}>{saving?"Saving doctor...":"Create doctor profile"}</button></div></div>;
}
