import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), name: text("name").notNull(), role: text("role", { enum: ["patient", "doctor", "admin"] }).notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const doctors = sqliteTable("doctors", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), specialty: text("specialty").notNull(), workingHours: text("working_hours", { mode: "json" }).notNull(), slotDurationMinutes: integer("slot_duration_minutes").notNull().default(30), calendarConnected: integer("calendar_connected", { mode: "boolean" }).default(false) });
export const appointments = sqliteTable("appointments", { id: text("id").primaryKey(), doctorName: text("doctor_name").notNull(), patientName: text("patient_name").notNull(), scheduledFor: text("scheduled_for").notNull(), status: text("status", { enum: ["held", "confirmed", "completed", "cancelled", "reschedule_required"] }).notNull().default("confirmed"), symptoms: text("symptoms").notNull(), urgency: text("urgency", { enum: ["low", "medium", "high"] }).notNull().default("low"), preVisitSummary: text("pre_visit_summary"), postVisitSummary: text("post_visit_summary"), holdExpiresAt: integer("hold_expires_at", { mode: "timestamp" }), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("appointments_doctor_slot_unique").on(table.doctorName, table.scheduledFor), index("appointments_patient_idx").on(table.patientName)]);
export const doctorLeaves = sqliteTable("doctor_leaves", { id: text("id").primaryKey(), doctorId: text("doctor_id").notNull(), leaveDate: text("leave_date").notNull(), reason: text("reason"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("doctor_leave_date_unique").on(table.doctorId, table.leaveDate)]);
export const prescriptions = sqliteTable("prescriptions", { id: text("id").primaryKey(), appointmentId: text("appointment_id").notNull().references(() => appointments.id), medicationName: text("medication_name").notNull(), dosage: text("dosage").notNull(), frequency: text("frequency").notNull(), durationDays: integer("duration_days").notNull(), instructions: text("instructions") });
export const notificationJobs = sqliteTable("notification_jobs", { id: text("id").primaryKey(), appointmentId: text("appointment_id").references(() => appointments.id), channel: text("channel", { enum: ["email", "calendar", "medication"] }).notNull(), payload: text("payload", { mode: "json" }).notNull(), status: text("status", { enum: ["pending", "processing", "delivered", "retrying", "dead_letter"] }).notNull().default("pending"), attempts: integer("attempts").notNull().default(0), nextAttemptAt: integer("next_attempt_at", { mode: "timestamp" }), idempotencyKey: text("idempotency_key").notNull().unique() });
export const calendarConnections = sqliteTable("calendar_connections", { id: text("id").primaryKey(), accountEmail: text("account_email").notNull(), accessToken: text("access_token").notNull(), refreshToken: text("refresh_token"), expiresAt: integer("expires_at", { mode: "timestamp" }), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("calendar_connections_email_unique").on(table.accountEmail)]);
export const calendarEvents = sqliteTable("calendar_events", { id: text("id").primaryKey(), appointmentId: text("appointment_id").notNull().references(() => appointments.id), accountEmail: text("account_email").notNull(), providerEventId: text("provider_event_id").notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("calendar_events_appointment_account_unique").on(table.appointmentId, table.accountEmail)]);
